name: Run Outlet Crawler

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 00:00 UTC = 한국 9AM
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install gspread oauth2client selenium beautifulsoup4
          sudo apt-get update
          sudo apt-get install -y unzip wget curl

      - name: Install matching Chrome & ChromeDriver
        run: |
          # Get Chrome version
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          echo "✅ Detected Chrome version: $CHROME_VERSION"

          # Download matching ChromeDriver
          DRIVER_URL="https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chromedriver-linux64.zip"
          wget -O chromedriver.zip $DRIVER_URL
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Run crawler
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_KEY }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > credentials.json
          python outlet_crawler.py
