name: Run Outlet Crawler

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 00:00 UTC → 한국 시간 09:00
  workflow_dispatch:     # 수동 실행 가능

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install gspread oauth2client beautifulsoup4 requests

      - name: Run crawler
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_KEY }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > credentials.json
          python outlet_crawler.py
